apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentry
  annotations:
    github.com/project-slug: appolon1908-hue/Sentry
spec:
  type: service
  lifecycle: production
  owner: appolon-platform
  system: codestra-production
